service: nestjs-lambda
 
frameworkVersion: '3'
 
plugins:
  - serverless-jetpack
  - serverless-offline
 
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
 
functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}